tests = [{ \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 1, \
            'ans': 0 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 3, \
            'ans': 2 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 2, \
            'ans': 3 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 6, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 7, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 10, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 4, \
            'ans': 6 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 8, \
            'ans': 6 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 9, \
            'ans': 8 \
        }, { \
            'file': 'test_cases/test1.txt', \
            'src': 1, \
            'dest': 5, \
            'ans': 9 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 1, \
            'ans': 0 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 2, \
            'ans': 3 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 3, \
            'ans': 2 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 4, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 5, \
            'ans': 5 \
        }, { \
            'file': 'test_cases/test2.txt', \
            'src': 1, \
            'dest': 6, \
            'ans': 5 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 2, \
            'ans': 1 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 3, \
            'ans': 2 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 4, \
            'ans': 3 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 5, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 6, \
            'ans': 4 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 7, \
            'ans': 3 \
        }, { \
            'file': 'test_cases/test3.txt', \
            'src': 1, \
            'dest': 8, \
            'ans': 2 \
        }]

quiz = [{ \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 7, \
            'ans': 2599 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 37, \
            'ans': 2610 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 59, \
            'ans': 2947 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 82, \
            'ans': 2052 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 99, \
            'ans': 2367 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 115, \
            'ans': 2399 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 133, \
            'ans': 2029 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 165, \
            'ans': 2442 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 188, \
            'ans': 2505 \
        }, { \
            'file': 'dijkstraData.txt', \
            'src': 1, \
            'dest': 197, \
            'ans': 3068 \
        }]
