tests = [{ \
            'file': 'test_cases/case0.in', \
            'ans': [3,3,0,0,0] \
        }, { \
            'file': 'test_cases/case1.in', \
            'ans': [3,3,3,0,0] \
        }, { \
            'file': 'test_cases/case2.in', \
            'ans': [3,3,2,0,0] \
        }, { \
            'file': 'test_cases/case3.in', \
            'ans': [3,3,1,1,0] \
        }, { \
            'file': 'test_cases/case4.in', \
            'ans': [7,1,0,0,0] \
        }, { \
            'file': 'test_cases/case5.in', \
            'ans': [6,3,2,1,0] \
        }, { \
            'file': 'test_cases/case6.in', \
            'ans': None \
        }, { \
            'file': 'test_cases/case7.in', \
            'ans': None \
        }, { \
            'file': 'test_cases/case8.in', \
            'ans': None \
        }, { \
            'file': 'test_cases/case9.in', \
            'ans': None \
        }, { \
            'file': 'test_cases/SCC_10000.txt', \
            'ans': [261,244,219,198,196] \
        }, { \
            'file': 'test_cases/SCC_100000.txt', \
            'ans': [63621,704,143,141,126] \
        }, { \
            'file': 'test_cases/SCC_400000.txt', \
            'ans': [268355,704,484,321,208] \
        }]
